### ISSUE TITLE
Add Code of Conduct to the landing page 

### ISSUE THREAD

**Issue by williln** [djangocon/2017.djangocon.us#1]
Preferably as a separate page that is linked to from the landing page. The text you need is here: https://2016.djangocon.us/coc/ (DjangoCon's Code of Conduct, The Short Version, and the Long Version). 

Thank you!

**Comment by KatherineMichel** [comment]
I would take care of it, but not quite sure yet how it's being served. Will play around with it.

**Comment by jefftriplett** [comment]
Everything is Jekyll based so you'll want to create a `coc.md` file with our COC (please remove the names and contact phone numbers) but https://2016.djangocon.us/coc/ should be a good starting point.

Then link to it at the bottom of the README.md and that should be a good start :)

**Comment by KatherineMichel** [comment]
Ok, it can be assigned to me then. I didn't know it could be served without an index.html.

**Comment by jefftriplett** [comment]
@KatherineMichel here was the fix on getting /coc/ to work. 

We won't use the default README.md as an index.html once the actual website is done. It made more sense when we just had one file.
