### ISSUE TITLE
Talk/Tutorial HTML

### ISSUE THREAD

**Issue by mtrythall** [djangocon/2017.djangocon.us#10]
We'll need to provide a basic format for Talk and Tutorial details.

**Comment by jefftriplett** [comment]
Please see #7 and let's confirm that we are on the same page about expectations. We provided real-work data upfront to ease any problems which could come from not having it.

**Comment by jessiofhall** [comment]
@jefftriplett no worries. This is a known requirement-- the front-end will play nicely with the data. Same goes for #7.

**Comment by mtrythall** [comment]
Only thing missing here is video and slide URL treatment.

**Comment by mtrythall** [comment]
I added slide and video buttons to the page and did some other clean up. This is good for review.
