### ISSUE TITLE
Header hides the anchors when we link to sections

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#106]
When we link to a section, the header hides our content enough that we can't see what we are linking to.

Take this FAQ example (this is one that came up mid-week): https://2017.djangocon.us/financial-aid/#frequently-asked-questions

![](https://www.evernote.com/shard/s27/sh/9faa9f39-c711-418d-ae87-3dd6f4bcb5e5/8e2b1d16d8a7b59d/res/41f16407-4fcb-4a5f-bef8-8c74e04fa9a5/skitch.png)

**Comment by mtrythall** [comment]
Easy fix. I'll hit this one this weekend.

**Comment by mtrythall** [comment]
PR for this here: https://github.com/djangocon/2017.djangocon.us/pull/110

No bulletproof solution since we can't use JS (murky browser support for `:target`), but this ought to work in most cases.
