### ISSUE TITLE
Close CFP + Financial Aid references

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#121]
We need to update the website to reflect that our CFP and Financial Aid deadlines have passed and our applications have closed.

We may want to use `{% comment %}` and `{% endcomment %}` blocks around some of the old copy to make updating for 2018 easier.

**Comment by KatherineMichel** [comment]
I went ahead and made a branch for this so that we can close down the links.

**Comment by KatherineMichel** [comment]
I think we can close this due to #123
