### ISSUE TITLE
Finish building out Why DjangoCon US? page

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#122]
Our goal with the *Why DjangoCon US* page is to help employees justify why attending our conference is worthwhile to their employers. This can be (and many, many others):

- Training (tutorials and talks) and learn from the developers who create the software. Post-CFP: we should highlight tutorials which have corporate value. 

- Talent if you are looking to hire there will be dozens of diverse people looking for jobs.

- Knowledge - being the first to learn about new technologies and more advanced techniques

- Help support the community which builds the tools you use

We have a starter page but we aren't quite there yet: https://2017.djangocon.us/why-djangocon-us/

We also have some example copy: https://docs.google.com/document/d/18Jk7JlKGDHh3TcIxlBi5DwP-WbOZ-IHYv11H6-p4p7A/edit 

Website styleguide: https://2017.djangocon.us/styleguide/

**Comment by williln** [comment]
@jefftriplett Is there a specific format or approach you think would be best here?

**Comment by jefftriplett** [comment]
@williln lets do a quick Slack chat on this some time. I think we want to do do a DSF blog post and highlight this along with tickets are on sale.

**Comment by williln** [comment]
@jefftriplett OK to close?
