### ISSUE TITLE
We need a ticket page

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#141]
Historically, we get asked a lot of questions about which tickets to buy. While I like having a *Buy Tickets* page, this doesn't quite fill in the information gap from people who want to know more about which they may purchase. We should considering bringing back some of the information from the 2016 page: https://2016.djangocon.us/tickets/

**Comment by rebkin05** [comment]
Some of that info (what ticket to pick and refund policy) is in this post and can maybe be cribbed from there: https://2017.djangocon.us/news/tickets-on-sale/ 

Also, I can link to the blog post more on Twitter instead of going straight to ti.to

**Comment by jefftriplett** [comment]
@rebkin05 good ideas!

**Comment by williln** [comment]
Since #146 was merged, I think this can be closed, yeah? cc @KatherineMichel

**Comment by KatherineMichel** [comment]
Looks good!
