### ISSUE TITLE
Refactor static build process

### ISSUE THREAD

**Issue by mtrythall** [djangocon/2017.djangocon.us#15]
Right now we're relying on Bower and NPM. We should drop Bower, in favor of NPM only.

We should also compress and concat Sass and JS files.

* [x] Ditch Bower
* [x] Move all Sass dependencies into NPM
* [x] Uglify CSS
* [ ] Move all JS dependencies into NPM
* [ ] Concat JS files
* [ ] Uglify JS

**Comment by chris-erickson** [comment]
Any limitations here?  Is gulp the preferred route to take?  Statically built or at runtime with something like compressor?

**Comment by mtrythall** [comment]
Part of the catch here is wanting as much of the process to run through Jekyll. I suspect Jekyll plugins can do most of what's here, and there are few JS dependencies (could be tracked in the README). I'd look at a Jekyll/Ruby-first approach so compilation and deployment to Github isn't hindered, as much as you can.

In general I would avoid Gulp. If you have to go with a JS-based build tool, basic NPM ought to be fine.
