### ISSUE TITLE
Import talks from PaperCall.io

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#17]
See this Issue for more info: https://github.com/djangocon/papercall-api-to-xls/issues/1

**Comment by jefftriplett** [comment]
@FlipperPA is this one you have time to work on or mentor someone through?

**Comment by jefftriplett** [comment]
cc @deatonjm @kennethlove and @toastdriven - Feel free to ping me if you have questions. The format looks like: https://raw.githubusercontent.com/djangocon/2017.djangocon.us/master/_posts/talks/2016-07-18-09-00-keynote-1.md 

and for tutorials: https://github.com/djangocon/2017.djangocon.us/blob/master/_posts/tutorials/2013-07-17-09-00-tutorial-1.md

**Comment by FlipperPA** [comment]
I'm making decent progress on this here: https://github.com/djangocon/papercall-api-import

@jefftriplett - did you want to keep the same format as last year for metadata, or should we use what PaperCall gives us? For example, last year did not have tags, this year does. 

The fields PaperCall provides by the API are: confirmed, created_at, id, rating, state, tag_list, trust, updated_at, and for the talk itself, abstract, audience_level, description, notes, talk_format, and title. I *think* more fields will be available once we turn off double-blind.

**Comment by deatonjm** [comment]
Hey Tim,

The API doesn't output the communication between raters and submitters? Maybe it will be after we reveal speakers like you said. I hope so because there is some super important info happening in that box... lol

Thanks for your work on this!!! I only have 150 more talks to rate lololol

Best,
deatz

**Comment by FlipperPA** [comment]
Howdy @deatonjm, they should be available eventually, but aren't currently provided because we're still in double-blind review mode.
