### ISSUE TITLE
Schedule: Some speakers have email instead of name

### ISSUE THREAD

**Issue by williln** [djangocon/2017.djangocon.us#173]
![charlotte](https://user-images.githubusercontent.com/2286304/27296621-769f3cda-54d6-11e7-9b25-3c788ab28f6a.PNG)
![kati](https://user-images.githubusercontent.com/2286304/27296622-76a42d08-54d6-11e7-867e-373fe91d81b4.PNG)
@KatherineMichel and Charlotte have email addresses instead of names and probably don't want their emails public.

Listing this as a blocker as it's a privacy issue.

**Comment by jefftriplett** [comment]
Fixed. Nice catch. cc @FlipperPA in case he wants to fix it in the export script for future confs.

**Comment by williln** [comment]
TY @jefftriplett!
