### ISSUE TITLE
Schedule: Orientation/Shyness talk

### ISSUE THREAD

**Issue by williln** [djangocon/2017.djangocon.us#174]
The orientation event and the "Shy Person's Guide to Tech Conferences" are in the same session, and I thought they would be in the ballroom where the keynote presentation will be. I'm not sure the best way to reflect this on the schedule, and I am not sure if Kojo is going to have Ed go first or second, but is it possible to edit the YAML so that they appear as one event on the schedule and Ed and Kojo are both mentioned? "Shy Person's Guide" should also be a link to a detail page like the other talks. 
![orientation](https://user-images.githubusercontent.com/2286304/27309536-3f7ab9b8-5509-11e7-800e-343cbe5a568b.PNG)

**Comment by jefftriplett** [comment]
This is semi-fixed, but I didn't mark it off yet because I haven't had time to fix the box style and add profile photos. Any other changes wanted? https://2017.djangocon.us/talks/

**Comment by jefftriplett** [comment]
Currently looks like: ![](https://www.evernote.com/shard/s27/sh/3437b276-2a3d-4c27-9883-b74914154725/58e55f12de5aceb5/res/3aa51a21-f644-4654-a62d-dcc1a7db03e2/skitch.png)

**Comment by williln** [comment]
I think what we have in "currently looks like" is pretty good! I'd love it if we were able to link to a detail page for orientation that gave info on what orientation was, the abstract for "shy person's guide," and Kojo and Ed's bios. I also think it's fine, since this is a separate event from the conference talks themselves, to have this styled NOT like the other talks (so w/o photo and name on the schedule page), but still have the title be a link to a detail page, if that is possible @jefftriplett

**Comment by jefftriplett** [comment]
The talk does link but it's not super obvious. If you hover between the ""'s then you can see the link. Still a work in progress. I'd like to get the Kojo and Ed's names linked up with the proper styles.

**Comment by kojoidrissa** [comment]
Speaking of profile photos, I need to setup a Gravatar account to make that happen for myself, don't I?

**Comment by jefftriplett** [comment]
@kojoidrissa yes you do.... ;)

I'll work on this over lunch. I'd like to have profile photos on it which should be doable, because science.

**Comment by jefftriplett** [comment]
I pushed a fix which puts photos by the talk. They don't share the same background style but I'm not sure if that's a problem or not.
