### ISSUE TITLE
Add Contributors

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#18]
Since we have guidelines: https://github.com/djangocon/2017.djangocon.us/blob/design/CONTRIBUTING.md 

- [ ] Update any leftover 2016 references to 2017 references
- [ ] Add some type of simplified / semi-automated way to generate these: https://github.com/djangocon/2016.djangocon.us-archived/blob/development/README.md#contributors -- I'd skip the contribution types and group everyone together. All contributors are great.

**Comment by KatherineMichel** [comment]
I could add this using the all-contributors-cli, similarly to last year but without the emoji keys and emojis- just 100px photo and name. I tried it locally and seemed to work, though had to add people individually via command line. List did not auto-generate. There are a few other similar node.js tools but presentation is not as nice imo.

**Comment by jefftriplett** [comment]
@KatherineMichel is this complete? I ran the script and it seemed to refresh everything. If so, let's close it.

**Comment by KatherineMichel** [comment]
I just ran it and it seems to be working right. I will close issue.
