### ISSUE TITLE
Guidebook integration

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#190]
To make life easier for next year, we'd like to generate some Guidebook friendly pages to dump:

- [x] Sponsors
- [x] Locations (our rooms)
- [x] Speakers
- [x] Schedules: Talks, tutorials, breaks, oh mai!

**Comment by jefftriplett** [comment]
Alternatively: https://support.guidebook.com/hc/en-us/articles/204880574-Pro-Tip-Export-Data-to-Edit-Content-Make-Links-and-Analyze-Survey-Responses

**Comment by FlipperPA** [comment]
This would allow us to import the schedule via a Spreadsheet or CSV: https://support.guidebook.com/hc/en-us/articles/115007936587-Add-Schedule-Sessions-Template-Import

We have most of the information in spreadsheet so it might be just a question of column matching. This one might be a good start: https://docs.google.com/spreadsheets/d/1RiJNS19K4Jg2u63pYpcAtXQ_KhSr6N_606zS3s8cI3Y/edit?usp=sharing

**Comment by jefftriplett** [comment]
I'm marketing this was as complete. We did a manual export of our data and Guidebook relies on some ids which make going from just CSV in and syncing back not very easy. Sadly, going to punt until next year.
