### ISSUE TITLE
Accessibility Page HTML

### ISSUE THREAD

**Issue by mtrythall** [djangocon/2017.djangocon.us#21]

**Comment by mtrythall** [comment]
My vote is *not* to do this page in favor of high level treatment and links to blog posts (since the info is venue/year dependent).

Thoughts on this @williln or @jefftriplett ?

You can see the treatment I'm using for accessibility info here:

http://djangocon.surge.sh/venue/

**Comment by williln** [comment]
I think this treatment looks fine, and the bullet points are able to call good attention to the accessibility information we have. Thoughts @ossanna16 @FlipperPA @rebkin05?

**Comment by mtrythall** [comment]
We could try an alternative treatment if there isn't much more information, as well.

**Comment by rebkin05** [comment]
The only other thing on our accessibility list is a lactation room, so I think this works! @mtrythall the venue team is meeting this weekend and will have real info for us soon.

**Comment by ossanna16** [comment]
This looks great! I like that it's short but contains everything we need (lactation room to be added I assume?) and the box and bullet points make it very visible. Good job @mtrythall!
