### ISSUE TITLE
Update speaker photos to remove blue power buttons

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#250]
Please see https://2017.djangocon.us/schedule/ for references. These can be github, twitter, or gravatar images.

**Comment by williln** [comment]
@jefftriplett Julia Looney is https://github.com/jlooney and would like to use that photo. I can't add her now as I'm about to leave, but FYI!

**Comment by jefftriplett** [comment]
@williln thank you, added in #265
