### ISSUE TITLE
Missing COC on repo

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#252]
We just need a `CODE_OF_CONDUCT.md` file to make this warning go away: https://www.evernote.com/l/ABsU14hcJnpNfb_vN4RNnDfMH_XR9izcnvs

**Comment by jefftriplett** [comment]
cc @williln @KatherineMichel

**Comment by williln** [comment]
@jefftriplett Is the text from https://2017.djangocon.us/coc/ fine or do we need one more specific to an online space like GH?

**Comment by jefftriplett** [comment]
Let's go with one of the defaults #253 unless someone has feels about one or the other.
