### ISSUE TITLE
Progressive Fonts

### ISSUE THREAD

**Issue by mtrythall** [djangocon/2017.djangocon.us#27]
> I'm also seeing some font/style pop-in when I load various pages. Might be my connection.

This is likely caused to Typekit fonts. We should find a good fallback system font and massage it into place. It seems that `wf-active` is applied to the HTML tag when Typekit has loaded, so don't apply the Program font until that class is active.

Note that Foundation's typography tools aren't setup for this, relying on a mixin that specifically applies the font, so we'll need to override that or compensate.

**Comment by jefftriplett** [comment]
I think this is fixed?

**Comment by mtrythall** [comment]
This is fixed. We're basically just hiding fonts until they load. No flicker, slightly better. This is likely something that needs to be solved *per year*, dependent upon fonts used.
