### ISSUE TITLE
RSS feed for News?

### ISSUE THREAD

**Issue by craigbruce** [djangocon/2017.djangocon.us#279]
Guidebook can display an RSS feed. I don't think our [News](https://2017.djangocon.us/news/) section includes one now? I can disable this feature in Guidebook, unless it does have a hidden RSS URL I can use?

**Comment by jefftriplett** [comment]
@craigbruce sure we do via: https://2017.djangocon.us/feed

**Comment by jefftriplett** [comment]
/me updated this in Guidebook and republished...

**Comment by craigbruce** [comment]
It didn't like the Jekyll RSS feed so I switched to a web view instead.
