### ISSUE TITLE
Financial Aid Page HTML

### ISSUE THREAD

**Issue by mtrythall** [djangocon/2017.djangocon.us#33]

**Comment by Nandutu** [comment]
i will work on this

**Comment by Nandutu** [comment]
hello some help here,
each time i create financialaid.html in _site am not successful in pushing it because it is added to .gitignore file. Question: what is the best location for me to include this file?

**Comment by KatherineMichel** [comment]
I don't think you need to change anything in _site. It's the compiled code. If you are creating a new HTML template or partial HTML template, it can go in _layouts.  If you are inserting markdown only into a pre-existing template, you can put the markdown file in _pages. You can look through the existing pages locally and look at the files in _layouts and _pages to see how they were generated. _posts is for blog posts and _includes is for global templates such as nav and footer.

**Comment by Nandutu** [comment]
ok thanks

**Comment by Nandutu** [comment]
Thanks

**Comment by KatherineMichel** [comment]
No problem. Jeff did some refactoring last night. He went ahead and moved the Financial Aid page code to markdown, but the questions/answers could still use some differentiation in markdown.

**Comment by jefftriplett** [comment]
Hi @Nandutu, I did some restructuring last night to try and make the layouts vs. pages less confusing. The page to look at is located here now: https://github.com/djangocon/2017.djangocon.us/blob/develop/_pages/financial-aid.md

There is plenty to do on the markdown file like converting some of the html to pure markdown and working with our [styleguide](https://2017.djangocon.us/styleguide/) to make the page more visually pleasing.

**Comment by KatherineMichel** [comment]
@Nandutu Here is a [GitHub Flavored Markdown explainer](https://guides.github.com/features/mastering-markdown/) and [cheat sheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf/). The hyperlinks can be changed to markdown and the questions could be changed from an ordered list to H3 headings (### Heading) perhaps. There is probably more than one way to do this though and maybe you have another idea.

**Comment by Nandutu** [comment]
@KatherineMichel @jefftriplett Thanks,
i have updated the html to purely markdown, please check it out https://github.com/djangocon/2017.djangocon.us/blob/develop/_pages/financial-aid.md

**Comment by KatherineMichel** [comment]
Looks good to me! I fixed a few typos. There were a couple of places where there was not a space in between the variable bracket and the next word, which made the words run together on the website page when rendering. Imo the Questions and Answers section looks really nice with the headings.

**Comment by Nandutu** [comment]
Okay....thanks
