### ISSUE TITLE
Contact Page HTML

### ISSUE THREAD

**Issue by mtrythall** [djangocon/2017.djangocon.us#34]

**Comment by mtrythall** [comment]
@jefftriplett @williln Do we still want a contact page?

We have it in the sitemap. The footer features an email address. Maybe that's good enough?

**Comment by craigbruce** [comment]
I'm -1 having a form that can send us email (read 99% spam)

**Comment by williln** [comment]
I think the email address in the footer is sufficient.

**Comment by williln** [comment]
@mtrythall I think this is okay to close then?
