### ISSUE TITLE
FAQs HTML Page

### ISSUE THREAD

**Issue by mtrythall** [djangocon/2017.djangocon.us#35]

**Comment by mtrythall** [comment]
@williln We'll need content for the FAQs page. I can put together a quick format for you.

**Comment by williln** [comment]
@mtrythall Thanks! I think Brent Schneider is working on that copy.

**Comment by mtrythall** [comment]
Dummy FAQs here: http://djangocon.surge.sh/faqs/

**Comment by jefftriplett** [comment]
I think the styles for this are fine. We pulled them into the https://2017.djangocon.us/financial-aid/#frequently-asked-questions page and I don't know if we are for certainly going to have a dedicated page but these are nice to have in case.

@jessiofhall I'm marking these as approved btw.
