### ISSUE TITLE
About HTML 

### ISSUE THREAD

**Issue by jessiofhall** [djangocon/2017.djangocon.us#5]
Front-end patterns for the About Page. to be delivered by @mtrythall and @kkellydesign

**Comment by mtrythall** [comment]
Notes here:

https://trello.com/c/4Fw8050Z/7-about-djangocon

Shortcut to content: 

https://docs.google.com/document/d/1MDf-F9G2PsgjKrRDtowo-eYAq_UlnPTZj0E9bTmaKBE/edit

**Comment by jefftriplett** [comment]
@rebkin05 / @williln are we good with the content here?

@craigbruce see anything else we need?

**Comment by rebkin05** [comment]
@jefftriplett ...there are a few small content changes I'd like to make--sorry! (Adding US to all references to DjangoCon, mostly). Doing those now in suggest mode so they stand out.

**Comment by williln** [comment]
@jefftriplett This page links to /about/accessibility, which will probably become just about/venue, but either way isn't baked yet; and to about/financial, which doesn't exist yet. So it seems like those three pages should go live together.

**Comment by williln** [comment]
@rebkin05 You can make those changes directly to the repo and just submit a PR if you want?

**Comment by jefftriplett** [comment]
If we need to build tickets off of this so that there's a clear line between LL and what our content is doing then I'm not against that. Whatever is the cleanest / easiest to communicate.

**Comment by rebkin05** [comment]
@williln ...I probably can do that

**Comment by craigbruce** [comment]
Content LGTM

**Comment by jefftriplett** [comment]
The "Pre-Conference" and "Conference Schedule" h2's don't appear to be styled. Please verify.

**Comment by williln** [comment]
@jefftriplett They were styled, but I think the classes were cancelling each other out or something because they looked weird. I edited the class to make those H2's match another one on the page and I think it looks better now.

**Comment by williln** [comment]
@rebkin05 Did you get the changes in that you wanted for this page?

**Comment by rebkin05** [comment]
@williln Yep, looks good!
