### ISSUE TITLE
Improve Map on Venue

### ISSUE THREAD

**Issue by mtrythall** [djangocon/2017.djangocon.us#53]
Currently the map on /venue/ is a static image. This might be better served as a Google Map with an InfoWindow, showing a picture of the venue, address, phone, etc, similar to what's here:

http://emberconf.com/location-and-hotels.html

This presents some problems that need to be addressed:

1. Styling the InfoWindow (if needed)
2. Ensuring the map has the right amount of details
3. Disabling scroll capture on mobile

Ideally *all* the important points for the year are reflected on the map, but in desktop mode on the hotel/venue is highlighted. Clicking something takes you to a full map. This requires a custom Google Map to be made.

**Comment by rlconley** [comment]
I'll take a stab at this.

**Comment by jefftriplett** [comment]
I'm going to mark this as complete. Feel free to update with a feature request going forward.
