### ISSUE TITLE
Card Sections 

### ISSUE THREAD

**Issue by KatherineMichel** [djangocon/2017.djangocon.us#58]
When the homepage is fullscreen on my laptop, the card-sections are sliding off the page 
![card-sections](https://cloud.githubusercontent.com/assets/4193054/24003058/6377109c-0a30-11e7-8d19-d886b8cb97e6.png)

**Comment by mtrythall** [comment]
@KatherineMichel This is weird!

I'm on a 5k screen and don't see this issue.

<img width="2484" alt="screenshot 2017-03-17 10 58 26" src="https://cloud.githubusercontent.com/assets/84750/24048907/b576934c-0b00-11e7-900f-f7461efbfba7.png">

Got any hints with regard to the CSS upon inspection?

**Comment by KatherineMichel** [comment]
It turns out I was looking at it on Canary Chrome. Not sure why it did that. It looks fine on regular Chrome. I will close this.
