### ISSUE TITLE
Venue HTML 

### ISSUE THREAD

**Issue by jessiofhall** [djangocon/2017.djangocon.us#6]
to be delivered by @mtrythall and @kkellydesign

**Comment by jefftriplett** [comment]
@rebkin05 / @williln / @craigbruce are we good?

**Comment by williln** [comment]
LGTM, but we need rec's from Brent and the Spokane team on places to highlight. We also probably want to hold off on confirming that we'll have childcare, since we haven't lined up a provider yet.

**Comment by craigbruce** [comment]
Looks good, but various placeholders need completing first.
