### ISSUE TITLE
Resolve home vs. home-full

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#68]
These two are similar enough yet I can't tell what is meant to be there  vs. what has changed over a few versions. Please take a merge them and comment out sections examples if they aren't current / fleshed out. 

- [ ] Resolve the layouts differences
- [ ] Resolve the pages differences
- [ ] Delete the deprecated versions.

**Comment by jessiofhall** [comment]
@mtrythall -- when you have time will you add notes here?
