### ISSUE TITLE
Configurize email links

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#69]
To help future proof the website, we should pull all email links into `_config.yml` and replace html references.

Examples of `_config.yml` vars:

- [x] contact_us_email: "hello@djangocon.us"
- [x] sponsors_email: "sponsors@djangocon.us"
- [x] visa_email: "visas@djangocon.us"

Then update all references in the templates to use:

- [x] {{ site.contact_us_email }}
- [x] {{ site.sponsors_email }}
- [x] {{ site.visa_email }}

The `mailto:` reference should be the key to find these or `@djangocon`.

**Comment by KatherineMichel** [comment]
I will work on this one.

**Comment by jefftriplett** [comment]
Thank you, I think this is covered now.
