### ISSUE TITLE
CoC: Styling and phrasing 

### ISSUE THREAD

**Issue by williln** [djangocon/2017.djangocon.us#75]
- [ ] Remove TL;DR header 
- [ ] Style opening paragraph the way the About opener is styled (a little larger) 
- [ ] Review CoC to make sure everything is covered. 
- [ ] Move "if you are being harassed" higher. That should be easier to find.

**Comment by KatherineMichel** [comment]
I really like the Need help? callout out. I'm re-opening this because there is too much space at the bottom of the page. I am looking at the layout patterns to see how to fix.

**Comment by mtrythall** [comment]
Problem with padding seems to be nested page wrappers.

<img width="376" alt="screenshot 2017-03-31 23 24 52" src="https://cloud.githubusercontent.com/assets/84750/24574995/530ee654-1669-11e7-9620-d57e21cd54be.png">

You only need one `content subpage-content` container

**Comment by KatherineMichel** [comment]
You're right. I think the problem is it's using two different layouts.

**Comment by williln** [comment]
I merged @KatherineMichel PR this morning. Kati, can you confirm this is ok to close?

**Comment by KatherineMichel** [comment]
I think so.
