### ISSUE TITLE
Financial Aid To-Do's 

### ISSUE THREAD

**Issue by williln** [djangocon/2017.djangocon.us#76]
- [x] Add "Apply" button close to top
- [x] Style FAQs so they are easier to read.

**Comment by KatherineMichel** [comment]
This falls along the lines of what @Nandutu has been doing in issue #33 if she is interested. There is an example button added to markdown on line 23 of https://github.com/djangocon/2017.djangocon.us/blob/develop/_pages/speaking.md ... click "Blame" to see the code.

**Comment by Nandutu** [comment]
FAQs @williln check out  https://github.com/djangocon/2017.djangocon.us/blob/develop/_pages/financial-aid.md still figuring out the button, @KatherineMichel can not seem to find "Blame"

**Comment by KatherineMichel** [comment]
Raw and Blame are buttons in the upper right hand corner of a file that you can click to see the different versions of the code @Nandutu. 
![raw-and-blame](https://cloud.githubusercontent.com/assets/4193054/24312940/dcc7d91c-10a8-11e7-94a5-e36d77bcf1ca.png)
.

**Comment by williln** [comment]
Thanks for your work everyone! I went ahead and added the final button since we're in the last week of the app being open, and I'm closing this issue.
