### ISSUE TITLE
Organizers: Link to their websites isn't showing up 

### ISSUE THREAD

**Issue by williln** [djangocon/2017.djangocon.us#77]

**Comment by KatherineMichel** [comment]
This could be added as an additional icon perhaps, maybe a little globe. I'm not sure where LL has obtained their svg icons though. Not sure about copyright issues. Or could be a hyperlink from name/photo?

`                {% if organizer.website != blank %}
                <li>
                  <a class="website" href="{{ organizer.website }}" target="_blank">
                    <svg class="website-icon"><use xlink:href="#website-icon"></use></svg>
                  </a>
                </li>
                {% endif %}`

**Comment by williln** [comment]
Or maybe just hyperlink the name? Not sure. @mtrythall are you using an icon sent like fontawesome for the icons? I glanced through the code and didn't see anything obvious...

**Comment by KatherineMichel** [comment]
This was fixed with PR #100

**Comment by mtrythall** [comment]
Social icons are added via a sprite map that gets added to the page. *Everything* should probably use this, but it's currently only setup for those icons.

This is the file: https://github.com/djangocon/2017.djangocon.us/blob/develop/_includes/social-icons.html

No, we aren't using fontawesome or anything (not a best practice anymore). We're using SVG. You can find a lot of icons from thenounproject.com, just make sure you provide attribution or buy them (mega cheap).
