### ISSUE TITLE
Venue: Add "Attractions" 

### ISSUE THREAD

**Issue by williln** [djangocon/2017.djangocon.us#78]
4 of them.

**Comment by williln** [comment]
Looks like it's being addressed in #97

**Comment by jefftriplett** [comment]
Re-opening since #97 was part of getting the website ready to launch.

**Comment by williln** [comment]
@brentschneider Are you still working on this? Do you need help?

**Comment by brentschneider** [comment]
Yes, I have a list of locations.
todo: need photos and perhaps categorize by type

**Comment by williln** [comment]
@brentschneider If you need help or other volunteers, reach out or email hello@!

**Comment by brentschneider** [comment]
[committed changes to my repo](https://github.com/brentschneider/2017.djangocon.us/commit/69ff1212cfd82b1c521b4d778e682893030439f4). @williln or @jefftriplett I have some questions regarding the branches before I submit a pull request.

**Comment by KatherineMichel** [comment]
The style looks a bit wonky. Obviously need photos for favorite spots. I wonder if could be limited by four or six and randomized?

**Comment by williln** [comment]
@brentschneider Thanks for your work on this! What we have now looks really good. 

I agree with @KatherineMichel that the number of attractions is a little long. Can we limit it to 4 or 6 (or randomize it so we show different ones each time) and also add photos?

**Comment by KatherineMichel** [comment]
It's easy to limit the number of places by adding limit:4 or limit:6. I thought the places could be shuffled by adding a custom Jekyll shuffle filter, but not sure if that will work. For one thing, sometimes with Jekyll random methods there is an issue with the randomness being generated at build-time instead of when page is refreshed.

**Comment by jefftriplett** [comment]
We might try adding category headings to break the long lists up. I think this would help to quickly see places to eat, get coffee, get a drink, do tourist things, etc.

**Comment by williln** [comment]
#147 limited the list of attractions to 8 by commenting some out in the yaml, and added photos, but didn't add category headings. IDK if we still want to mess with this section, or just close this issue?

**Comment by jefftriplett** [comment]
This seems baked. Any future updates can easily be feature tickets. Thanks for the help y'all!
