### ISSUE TITLE
Organizers HTML 

### ISSUE THREAD

**Issue by jessiofhall** [djangocon/2017.djangocon.us#8]
to be delivered by @mtrythall and @kkellydesign

**Comment by mtrythall** [comment]
@kkellydesign can run with this one. Via Lacey:

> Could be a photo bank with names[/position] and link to Twitter handles or personal websites or something.

- [ ] Organizer photo
- [ ] Organizer name
- [ ] Organizer description (will be optional)
- [ ] Links (perhaps via icons)

**Comment by jefftriplett** [comment]
I added some organizer yml info: https://github.com/djangocon/2017.djangocon.us/blob/design/_data/organizers.yml to help fill in the gaps.

**Comment by mtrythall** [comment]
HTML/Design-wise this is done. It just needs:

- [ ] Copy for the intro
- [ ] All organizer info filled out
- [ ] A proper meta description

**Comment by jessiofhall** [comment]
@mtrythall want me to create a Trello assignment for Lacey?

**Comment by jefftriplett** [comment]
Can we add a website url to the profiles? https://github.com/djangocon/2017.djangocon.us/blob/design/_data/organizers.yml#L9

I'll queue people to start updating their info if that doesn't add too much overhead.

**Comment by jefftriplett** [comment]
@rebkin05 / @williln it looks like we need content for this too: https://2017.djangocon.us/about/organizers/
