### ISSUE TITLE
Making the site data-driven

### ISSUE THREAD

**Issue by KatherineMichel** [djangocon/2017.djangocon.us#93]
A few more possible ways to make the site data-driven. Perhaps not all are applicable. Please add if think of something.
- navigation
- talks (regular/lightning)
- tutorials
- sprints
- attractions

**Comment by jefftriplett** [comment]
I believe we covered most of these: 

- [x] The navs are DRY via an `includes/nav.html`. We could make pull them into a data file, but that might not be worth the effort if we only have a top nav.
- [x] Talks + Tutorials (`_posts/talks/*` and `_posts/tutorials/*`)
- [ ] We will need to finish the sprints page though but that can be a page. 
- [ ] We need to fill out the lightning talk page. 
- [x] Attractions (`_data/places.yml`).

**Comment by jefftriplett** [comment]
I think this is mostly done. Cc'ing @kojoidrissa in case he has ideas for the lightning talk portion of the website. 

I have a basic sprint page working now too. We also need a sprint chair to help with this (for the text copy).
