### ISSUE TITLE
Homepage news styles are off

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#99]
The styles of the "Latest News" boxes look off.

![screencapture-localhost-8000-1490659572870](https://cloud.githubusercontent.com/assets/50527/24386975/13cb5b00-1338-11e7-8c1a-a3da7084355d.png)

**Comment by mtrythall** [comment]
Fix for this was pushed to develop. Please verify.

![homepage](https://cloud.githubusercontent.com/assets/84750/24405820/3705978c-1394-11e7-998c-76bff1736929.png)

**Comment by jefftriplett** [comment]
Thank you this is indeed fixed now.
